services:
  app:
    container_name: reelsmaker 

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7501:7501"
    volumes:
      - ./tmp:/app/tmp
      - ./images:/app/images
      - ./data:/app/data  # Mount the whole data directory instead
    environment:      
      - BACKGROUND_MUSIC_PATH=/app/assets/music
      - BACKGROUND_MUSIC_ENABLED=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}      
      - VOICE_PROVIDER=kokoro  # Set default voice provider to Kokoro
      - KOKORO_SERVICE_URL=http://kokoro_service:8880  # URL for the service
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - MAX_BG_VIDEOS=${MAX_BG_VIDEOS}
      # CPU optimization settings
      - OMP_NUM_THREADS=8
      - MKL_NUM_THREADS=8
      - NUMEXPR_NUM_THREADS=8
      - PYTORCH_ENABLE_CPU_FALLBACK=1
    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:7501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    networks:
      reels-network:
        aliases:
          - reelsmaker
      crown-network:
        aliases:
          - reelsmaker
        
    command: >
      bash -c "
        streamlit run reelsmaker.py --server.port=7501 --server.address=0.0.0.0
      "

networks:
  reels-network:  
    driver: bridge
  crown-network:
    external: true